# Generated by Django 4.1.13 on 2024-01-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sporting Dog', 'Sporting Dog'), ('Hound Dog', 'Hound Dog'), ('Working Dog', 'Working Dog'), ('Terrier Group', 'Terrier Group'), ('Toy Group', 'Toy Group'), ('Non-Sporting Group', 'Non-Sporting Group'), ('Herding Group', 'Herding Group'), ('Miscellaneous Class', 'Miscellaneous Class'), ('Foundation Stock Service', 'Foundation Stock Service')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('character', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=30)),
                ('life_expentancy', models.CharField(max_length=30)),
                ('aggressiveness', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=255)),
                ('image0', models.CharField(max_length=255, null=True)),
                ('image1', models.CharField(max_length=255, null=True)),
                ('image2', models.CharField(max_length=255, null=True)),
                ('akc_link', models.CharField(max_length=255)),
                ('origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breed_details.dogorigin')),
                ('type_id', models.ForeignKey(choices=[('Sporting Dog', 'Sporting Dog'), ('Hound Dog', 'Hound Dog'), ('Working Dog', 'Working Dog'), ('Terrier Group', 'Terrier Group'), ('Toy Group', 'Toy Group'), ('Non-Sporting Group', 'Non-Sporting Group'), ('Herding Group', 'Herding Group'), ('Miscellaneous Class', 'Miscellaneous Class'), ('Foundation Stock Service', 'Foundation Stock Service')], on_delete=django.db.models.deletion.CASCADE, to='breed_details.dogtype')),
            ],
        ),
    ]
