# Generated by Django 4.1.13 on 2024-01-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breed_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreeddetails',
            name='origin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='breed_details.dogorigin'),
        ),
        migrations.AlterField(
            model_name='dogorigin',
            name='origin_place',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
