# Generated by Django 4.1.13 on 2024-01-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breed_details', '0002_alter_dogbreeddetails_origin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogbreeddetails',
            name='origin_id',
        ),
        migrations.AlterField(
            model_name='dogbreeddetails',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breed_details.dogtype'),
        ),
    ]
