# Generated by Django 4.1.13 on 2024-01-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_details', '0003_remove_dogbreeddetails_origin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreeddetails',
            name='aggressiveness',
            field=models.CharField(max_length=50),
        ),
    ]
